Controllers/PriceLightAlertController.cs
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Identity.Web;
using Microsoft.Graph;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Hosting;
using HueApi.Models;
using System;
using Tehotasapaino.Models;
using TempDataExtensions;

namespace Tehotasapaino.Controllers
{
    [Authorize]
    public class PriceLightAlertController : Controller
    {
        private readonly ILogger<PriceLightAlertController> _logger;
        private readonly GraphServiceClient _graphServiceClient;
        private readonly UserService _userService;
        private readonly HueLightService _hueLightService;

        public PriceLightAlertController(ILogger<PriceLightAlertController> logger,
                          GraphServiceClient graphServiceClient, UserService userService,
                           HueLightService hueLightService)
        {
            _logger = logger;
            _graphServiceClient = graphServiceClient;
            _userService = userService;
            _hueLightService = hueLightService;
        }

        [AuthorizeForScopes(ScopeKeySection = "DownstreamApi:Scopes")]
        public async Task<IActionResult> UserPriceAlertConfigurator()
        {
            User user = await _graphServiceClient.Me.Request().GetAsync();
            ViewData["ApiResult"] = user.DisplayName;

            try
            {

                UserPriceAlertConfiguratorViewModel priceAlertViewModel = await _userService.CreatePriceAlertViewModel(user);
                return View(priceAlertViewModel);

            }
            catch (Exception)
            {

                TempData.Put("UserMessage", new SuccessMessage()
                { CssClassName = "alert-danger", Title = "Error!", DisplayMessage = $"You have no access to service" });
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost, ActionName("lightstate")]
        [AuthorizeForScopes(ScopeKeySection = "DownstreamApi:Scopes")]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> SetLightState([FromBody] LightStateFromTestPage requestedLightState)
        {
            _logger.LogInformation($"POST lightstate received {requestedLightState}");
            try
            {
                User user = await _graphServiceClient.Me.Request().GetAsync();
                HuePutResponse response = await _hueLightService.SetAlertLightToDesiredState(user, requestedLightState);

                if (response.HasErrors)
                {
                    _logger.LogInformation($"Problems {response.Errors}");
                    return StatusCode(418, $"{response.Data} and {response.Errors}");
                }

                return Ok();

            }
            catch (Exception e)
            {
                _logger.LogInformation($"Problems {e}");
                return StatusCode(500, e.StackTrace);
            }
        }

        [HttpPost, ActionName("savealertprice")]
        [AuthorizeForScopes(ScopeKeySection = "DownstreamApi:Scopes")]
        public async Task<IActionResult> SaveAlertPrice()
        {
            _logger.LogInformation($"POST save price received");

            User user = await _graphServiceClient.Me.Request().GetAsync();

            TempData.Put("UserMessage", new SuccessMessage()
            { CssClassName = "alert-success", Title = "Success!", DisplayMessage = $"{user.DisplayName} your new alert price have been set!" });
            return RedirectToAction("Index", "Home");
        }
    }
}

Views/Shared/_Layout.cshtml
@using TempDataExtensions;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
    <title>@ViewData["Title"] - Tehotasapaino</title>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" asp-append-version="true" href="~/css/style.css" />
</head>
<body>
    @if (TempData.Get<SuccessMessage>("UserMessage") != null)
    {
        var message = TempData.Get<SuccessMessage>("UserMessage") as Tehotasapaino.Models.SuccessMessage;
        <div class="alert @message.CssClassName d-flex align-items-center alert-dismissible fade show" role="alert">
            <i class="bi bi-file-earmark-check-fill me-2" width="2em" height="2em"></i>
            <div><strong>@message.Title</strong> @message.DisplayMessage</div>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">&times;</button>


        </div>
    }
    <div id="JSAlertPlaceholder" style="z-index:2000; position:absolute; width:100%;"></div>
    <header>
        <nav class="navbar navbar-expand navbar-light justify-content-center p-0">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link h3" style="@(ViewData["HomeStyle"])" href="@Url.Action("Index", "Home")">Home <span class="sr-only"></span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link h3" style="@(ViewData["PriceAlertStyle"])" href="@Url.Action("UserPriceAlertConfigurator", "PriceLightAlert")">Price alerts</a>
                </li>

            </ul>

        </nav>
    </header>
    <div class="container mt-3 mb-3 text-center">
        @RenderBody()
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>